import type {
  Badge,
  Block,
  EarnedBadge,
  EngineEvent,
  Entity,
  LinkItem,
  Relationship,
} from "./types";

export const entities: Entity[] = [
  {
    id: "e-andrea",
    handle: "andrea",
    name: "Andrea Dailey",
    type: "person",
    tagline: "Building brands out loud — work, play, and everything between",
    initials: "AD",
    theme: { accent: "#ef4444", pattern: "dots" },
    tags: ["builder", "red-things", "90s-rock", "boston-terrier-energy"],
    streak: 12,
  },
  {
    id: "e-antiwhelm",
    handle: "antiwhelm",
    name: "antiwhelm",
    type: "brand",
    tagline: "Cut the noise. Build what matters.",
    initials: "aw",
    theme: { accent: "#ef4444", pattern: "diamond" },
    tags: ["calm", "systems", "ssme"],
  },
  {
    id: "e-aip",
    handle: "andreainpublic",
    name: "andreainpublic.com",
    type: "brand",
    tagline: "Building brands out loud",
    initials: "a.",
    theme: { accent: "#f43f5e", pattern: "diagonal" },
    tags: ["in-public", "real-time"],
  },
  {
    id: "e-streamo",
    handle: "streamo",
    name: "Streamo.gg",
    type: "brand",
    tagline: "Vibe is the algorithm",
    initials: "S",
    theme: { accent: "#d946ef", pattern: "grid" },
    tags: ["good-vibes", "community"],
  },
  {
    id: "e-vibetags",
    handle: "vibetags",
    name: "VibeTags",
    type: "product",
    tagline: "Tag your vibe. Find your people.",
    initials: "VT",
    theme: { accent: "#14b8a6", pattern: "dots" },
    tags: ["discovery", "taste"],
  },
  {
    id: "e-pixelpress",
    handle: "pixelpress",
    name: "Pixel Press Books",
    type: "brand",
    tagline: "Small press. Real shelves.",
    initials: "PP",
    theme: { accent: "#f59e0b", pattern: "diagonal" },
    tags: ["books", "indie-press"],
  },
  {
    id: "e-stop",
    handle: "stop",
    name: "STOP",
    type: "product",
    tagline: "The book — and the quote cards it shipped with",
    initials: "ST",
    theme: { accent: "#ef4444", pattern: "none" },
    tags: ["book", "quote-cards"],
  },
];

export const relationships: Relationship[] = [
  { from: "e-aip", to: "e-antiwhelm", kind: "parent" },
  { from: "e-vibetags", to: "e-streamo", kind: "parent" },
  { from: "e-andrea", to: "e-antiwhelm", kind: "owner" },
  { from: "e-andrea", to: "e-aip", kind: "owner" },
  { from: "e-andrea", to: "e-streamo", kind: "owner" },
  { from: "e-stop", to: "e-pixelpress", kind: "parent" },
  { from: "e-andrea", to: "e-pixelpress", kind: "owner" },
];

export const blocks: Block[] = [
  {
    id: "b-now",
    entityId: "e-andrea",
    facet: "work",
    title: "Now",
    body: "Building the profile engine, in public. One infrastructure for every profile I run.",
  },
  {
    id: "b-hire",
    entityId: "e-andrea",
    facet: "work",
    title: "Work with me",
    body: "Hire me directly — strategy, brand builds, shipping. No agency in the middle, no 50% cut.",
    cta: "Book direct",
  },
  {
    id: "b-playing",
    entityId: "e-andrea",
    facet: "play",
    title: "Now playing",
    body: "Ranked nights on Streamo. Good vibes, great plays.",
  },
  {
    id: "b-stop",
    entityId: "e-andrea",
    facet: "life",
    title: "STOP book",
    body: "Quote cards shipping — 18 captions in progress.",
  },
  {
    id: "b-made",
    entityId: "e-andrea",
    facet: "stuff",
    title: "Things I made",
    body: "Books, tools, drops. Buy direct from the maker.",
    cta: "Shop",
  },
  {
    id: "b-aw-about",
    entityId: "e-antiwhelm",
    facet: "work",
    title: "About",
    body: "The umbrella over Work, Life, Play, and Products. Simple. Scalable. Minimal. Effective.",
  },
  {
    id: "b-aw-miles",
    entityId: "e-antiwhelm",
    facet: "work",
    title: "Milestones",
    body: "Atla modules live. trymvp.co shipped.",
  },
  {
    id: "b-aip-about",
    entityId: "e-aip",
    facet: "work",
    title: "About",
    body: "The tech changes daily. The goal doesn't. Building in public, in real time.",
  },
  {
    id: "b-aip-tag",
    entityId: "e-aip",
    facet: "work",
    title: "Taglines",
    body: "Building brands out loud",
  },
  {
    id: "b-aip-stack",
    entityId: "e-aip",
    facet: "work",
    title: "Stack",
    body: "Next.js, Supabase, Tailwind",
  },
  {
    id: "b-st-about",
    entityId: "e-streamo",
    facet: "play",
    title: "About",
    body: "The gaming community built on vibe. Discover streamers, collect, compete, connect.",
  },
  {
    id: "b-st-drops",
    entityId: "e-streamo",
    facet: "play",
    title: "Culture drops",
    body: "VibeTags, live rooms, moments",
  },
  {
    id: "b-vt-what",
    entityId: "e-vibetags",
    facet: "stuff",
    title: "What it does",
    body: "Vibe tags for streamer discovery on Streamo.",
    cta: "Try it",
  },
  {
    id: "b-vt-log",
    entityId: "e-vibetags",
    facet: "stuff",
    title: "Changelog",
    body: "v2 shipped — tag search and vibe matching",
  },
  {
    id: "b-vt-road",
    entityId: "e-vibetags",
    facet: "stuff",
    title: "Roadmap",
    body: "Vote on what gets built next",
  },
  {
    id: "b-books",
    entityId: "e-andrea",
    facet: "stuff",
    title: "Books",
    body: "STOP — the book and its quote cards. Signed copies, direct from me.",
    cta: "Get the book",
  },
  {
    id: "b-pp-about",
    entityId: "e-pixelpress",
    facet: "work",
    title: "About",
    body: "Indie press for books that cut the noise. Author-owned, reader-direct.",
  },
  {
    id: "b-stop-about",
    entityId: "e-stop",
    facet: "stuff",
    title: "About the book",
    body: "Stop doing what doesn't matter. The framework, the stories, the receipts.",
    cta: "Buy direct",
  },
  {
    id: "b-stop-cards",
    entityId: "e-stop",
    facet: "stuff",
    title: "Quote cards",
    body: "18 cards from the book — share them, post them, print them.",
  },
];

export const links: LinkItem[] = [
  { entityId: "e-andrea", label: "andreainpublic.com", url: "https://andreainpublic.com" },
  { entityId: "e-andrea", label: "Streamo.gg", url: "https://streamo.gg" },
  { entityId: "e-andrea", label: "antiwhelm.com", url: "https://antiwhelm.com" },
  { entityId: "e-aip", label: "andreainpublic.com", url: "https://andreainpublic.com" },
  { entityId: "e-antiwhelm", label: "antiwhelm.com", url: "https://antiwhelm.com" },
  { entityId: "e-streamo", label: "streamo.gg", url: "https://streamo.gg" },
  { entityId: "e-vibetags", label: "streamo.gg", url: "https://streamo.gg" },
  { entityId: "e-pixelpress", label: "andreainpublic.com", url: "https://andreainpublic.com" },
  { entityId: "e-stop", label: "Get it at andreainpublic.com", url: "https://andreainpublic.com" },
];

export const events: EngineEvent[] = [
  {
    id: "ev-1",
    entityId: "e-andrea",
    facet: "work",
    kind: "shipped",
    label: "Shipped VibeTags v2 on Streamo",
    xp: 50,
    at: "Jun 9",
  },
  {
    id: "ev-2",
    entityId: "e-andrea",
    facet: "work",
    kind: "shipped",
    label: "Profile engine schema drafted",
    xp: 50,
    at: "Jun 8",
  },
  {
    id: "ev-3",
    entityId: "e-andrea",
    facet: "play",
    kind: "streamed",
    label: "Friday vibe session — 3 hours",
    xp: 15,
    at: "Jun 6",
  },
  {
    id: "ev-4",
    entityId: "e-andrea",
    facet: "life",
    kind: "wrote",
    label: "6 quote-card captions for STOP",
    xp: 10,
    at: "Jun 5",
  },
  {
    id: "ev-5",
    entityId: "e-andrea",
    facet: "stuff",
    kind: "sold",
    label: "Sold 3 print bundles, direct",
    xp: 25,
    at: "Jun 4",
  },
  {
    id: "ev-6",
    entityId: "e-andrea",
    facet: "work",
    kind: "shipped",
    label: "Atla relationships module live",
    xp: 50,
    at: "Jun 2",
  },
  {
    id: "ev-7",
    entityId: "e-andrea",
    facet: "play",
    kind: "streamed",
    label: "Among Us community night",
    xp: 15,
    at: "May 30",
  },
  {
    id: "ev-8",
    entityId: "e-andrea",
    facet: "life",
    kind: "wrote",
    label: "STOP chapter 7 revision",
    xp: 10,
    at: "May 28",
  },
  {
    id: "ev-9",
    entityId: "e-vibetags",
    facet: "stuff",
    kind: "shipped",
    label: "v2 released — tag search",
    xp: 50,
    at: "Jun 9",
  },
  {
    id: "ev-10",
    entityId: "e-vibetags",
    facet: "stuff",
    kind: "shipped",
    label: "v1.4 — vibe matching beta",
    xp: 50,
    at: "May 22",
  },
  {
    id: "ev-11",
    entityId: "e-streamo",
    facet: "play",
    kind: "shipped",
    label: "Moments spike detection live",
    xp: 50,
    at: "Jun 3",
  },
  {
    id: "ev-12",
    entityId: "e-stop",
    facet: "stuff",
    kind: "shipped",
    label: "Quote cards — first batch out",
    xp: 50,
    at: "Jun 7",
  },
  {
    id: "ev-13",
    entityId: "e-pixelpress",
    facet: "work",
    kind: "shipped",
    label: "STOP cover locked",
    xp: 50,
    at: "Jun 1",
  },
];

export const badges: Badge[] = [
  { id: "bg-early", name: "Early builder", desc: "Building since day one", icon: "🏗️" },
  { id: "bg-streak", name: "Ship streak ×7", desc: "Shipped 7 days straight", icon: "🔥" },
  { id: "bg-proof", name: "Receipts", desc: "100 proof-of-work events logged", icon: "🧾" },
  { id: "bg-1k", name: "1k receipts", desc: "1,000 proof-of-work events logged", icon: "🧾" },
  { id: "bg-legend", name: "Legend", desc: "You'll know when you get there", icon: "👑" },
];

export const earnedBadges: EarnedBadge[] = [
  { entityId: "e-andrea", badgeId: "bg-early" },
  { entityId: "e-andrea", badgeId: "bg-streak" },
  { entityId: "e-andrea", badgeId: "bg-proof" },
];
