import type {
  ActivityUpdate,
  House,
  HouseItem,
  HouseLink,
  HouseModule,
  HouseRelationship,
  ScheduleItem,
} from "./types";

export const houses: House[] = [
  {
    id: "house-andrea",
    handle: "andrea-dailey",
    name: "Andrea Dailey",
    type: "person",
    shortDescription: "Builder at heart. Systems thinker. Creator across media.",
    description:
      "The person behind the work: building systems, brands, books, apps, products, and the occasional world.",
    initials: "AD",
    primaryColor: "#d22f2f",
    status: "building",
    owner: "Andrea Dailey",
    tags: ["builder", "systems", "media", "products"],
    vibes: ["focused", "creative", "experimental"],
    rooms: ["identity", "positioning", "proof", "work", "products", "links", "schedule", "contact", "activity"],
    visibility: "public",
  },
  {
    id: "house-building-empires",
    handle: "building-empires",
    name: "Building Empires",
    type: "brand",
    shortDescription: "Tools, content, profiles, and a future marketplace for builders.",
    description:
      "Building Empires is the public site for useful tools and content now, with public profiles next and a marketplace path in v2.",
    initials: "B",
    primaryColor: "#ff6a00",
    status: "building",
    owner: "Andrea Dailey",
    tags: ["tools", "content", "profiles", "marketplace"],
    vibes: ["bold", "minimal", "focused"],
    rooms: ["identity", "positioning", "proof", "products", "offers", "schedule", "support", "links", "activity"],
    visibility: "public",
  },
  {
    id: "house-andrea-in-public",
    handle: "andrea-in-public",
    name: "Andrea in Public",
    type: "brand",
    shortDescription: "Build products out loud. Shipping weekly.",
    description:
      "The public operating layer for essays, build logs, useful lessons, products, experiments, and the work behind the work.",
    initials: "A",
    primaryColor: "#ff2a2a",
    status: "live",
    owner: "Andrea Dailey",
    tags: ["build-log", "essays", "weekly-ships", "public-work"],
    vibes: ["focused", "minimal", "experimental"],
    rooms: ["identity", "positioning", "proof", "work", "products", "offers", "posts", "links", "contact", "activity"],
    visibility: "public",
  },
  {
    id: "house-simplifiedworks",
    handle: "simplifiedworks",
    name: "SimplifiedWorks",
    type: "company",
    shortDescription: "Simple systems for work, products, and operations.",
    description:
      "The work systems profile for Atla, Imprint, Inbetween, and the SSME operating approach.",
    initials: "S",
    primaryColor: "#0A2F78",
    status: "live",
    owner: "Andrea Dailey",
    tags: ["systems", "work", "operations", "ssme"],
    vibes: ["minimal", "focused", "calm"],
    rooms: ["identity", "positioning", "proof", "products", "offers", "links", "contact", "activity"],
    visibility: "public",
  },
  {
    id: "house-atla",
    handle: "atla",
    name: "Atla",
    type: "product",
    shortDescription: "A work OS for projects, products, records, and teams.",
    description:
      "A SimplifiedWorks product for mapping work, profiles, records, projects, reports, and reusable operating systems.",
    initials: "A",
    primaryColor: "#38BDF8",
    status: "live",
    owner: "SimplifiedWorks",
    tags: ["work-os", "projects", "records", "ai"],
    vibes: ["focused", "minimal", "bold"],
    rooms: ["identity", "positioning", "proof", "work", "products", "reports", "support", "links", "activity"],
    visibility: "public",
  },
  {
    id: "house-imprint",
    handle: "imprint",
    name: "Imprint",
    type: "product",
    shortDescription: "Books, author systems, and publishing workflows.",
    description:
      "The book and publishing product lane for turning manuscripts, companion products, and author worlds into cleaner shelves.",
    initials: "I",
    primaryColor: "#ffae00",
    status: "building",
    owner: "SimplifiedWorks",
    tags: ["books", "publishing", "authors", "products"],
    vibes: ["creative", "minimal", "focused"],
    rooms: ["identity", "positioning", "proof", "books", "products", "offers", "links", "activity"],
    visibility: "public",
  },
  {
    id: "house-inbetween",
    handle: "inbetween",
    name: "Inbetween",
    type: "app",
    shortDescription: "Meet in the middle.",
    description:
      "A simple app for finding a fair meeting spot between two locations, without the guessing.",
    initials: "I",
    primaryColor: "#A8C4A2",
    status: "live",
    owner: "SimplifiedWorks",
    tags: ["app", "places", "planning"],
    vibes: ["calm", "minimal", "social"],
    rooms: ["identity", "positioning", "proof", "links", "contact", "activity"],
    visibility: "public",
  },
  {
    id: "house-streamo",
    handle: "streamo",
    name: "Streamo",
    type: "community",
    shortDescription: "Vibe is the algorithm.",
    description:
      "A gamer and creator product world for streams, vibe matching, creator links, clips, sections, and community energy.",
    initials: "S",
    primaryColor: "#EC4899",
    status: "live",
    owner: "PlaywaveStudios",
    tags: ["gaming", "creators", "community", "vibes"],
    vibes: ["playful", "competitive", "social"],
    rooms: ["identity", "positioning", "proof", "games", "streams", "products", "schedule", "links", "activity"],
    visibility: "public",
  },
  {
    id: "house-playwave",
    handle: "playwavestudios",
    name: "PlaywaveStudios",
    type: "studio",
    shortDescription: "Cinematic media, music, and digital drops.",
    description:
      "The studio profile for Playwave Radio, Streamo, media experiments, channels, shows, and creator-friendly listening lanes.",
    initials: "P",
    primaryColor: "#8B5CF6",
    status: "live",
    owner: "Andrea Dailey",
    tags: ["studio", "media", "music", "games"],
    vibes: ["creative", "playful", "experimental"],
    rooms: ["identity", "positioning", "proof", "channels", "products", "schedule", "links", "activity"],
    visibility: "public",
  },
  {
    id: "house-habits",
    handle: "habits-that-matter",
    name: "Habits That Matter",
    type: "brand",
    shortDescription: "Useful habits for a happier life.",
    description:
      "The habit, book, store, course, journal, and essay profile for small useful moves in real life.",
    initials: "H",
    primaryColor: "#8faa88",
    status: "live",
    owner: "Andrea Dailey",
    tags: ["habits", "books", "store", "life"],
    vibes: ["calm", "cozy", "minimal"],
    rooms: ["identity", "positioning", "proof", "books", "shop", "offers", "posts", "support", "links", "activity"],
    visibility: "public",
  },
  {
    id: "house-stop",
    handle: "stop",
    name: "STOP Collection",
    type: "book",
    shortDescription: "A collection of STOP books, journals, and tools.",
    description:
      "The STOP product profile: books, quote cards, companion products, journals, and shop-ready formats.",
    initials: "S",
    primaryColor: "#050505",
    status: "selling",
    owner: "Habits That Matter",
    tags: ["book", "collection", "journal", "shop"],
    vibes: ["calm", "focused", "minimal"],
    rooms: ["identity", "positioning", "proof", "books", "shop", "support", "links", "activity"],
    visibility: "public",
  },
  {
    id: "house-whatdeployed",
    handle: "whatdeployed",
    name: "WhatDeployed",
    type: "product",
    shortDescription: "Plain-English signal for what shipped.",
    description:
      "A useful software and AI signal index that tracks recent deployments, product shifts, and what changed.",
    initials: "W",
    primaryColor: "#148f4b",
    status: "live",
    owner: "Andrea Dailey",
    tags: ["ai", "software", "signals", "deployments"],
    vibes: ["focused", "minimal", "experimental"],
    rooms: ["identity", "positioning", "proof", "posts", "links", "activity"],
    visibility: "public",
  },
];

export const relationships: HouseRelationship[] = [
  { from: "house-andrea", to: "house-building-empires", kind: "owner" },
  { from: "house-andrea", to: "house-andrea-in-public", kind: "owner" },
  { from: "house-andrea", to: "house-simplifiedworks", kind: "owner" },
  { from: "house-andrea", to: "house-playwave", kind: "owner" },
  { from: "house-andrea", to: "house-habits", kind: "owner" },
  { from: "house-andrea", to: "house-whatdeployed", kind: "owner" },
  { from: "house-atla", to: "house-simplifiedworks", kind: "parent" },
  { from: "house-imprint", to: "house-simplifiedworks", kind: "parent" },
  { from: "house-inbetween", to: "house-simplifiedworks", kind: "parent" },
  { from: "house-streamo", to: "house-playwave", kind: "parent" },
  { from: "house-stop", to: "house-habits", kind: "parent" },
  { from: "house-andrea-in-public", to: "house-building-empires", kind: "related" },
];

export const modules: HouseModule[] = [
  {
    id: "m-be-about",
    houseId: "house-building-empires",
    room: "identity",
    title: "The public site",
    body: "Building Empires starts as a place for tools and useful content, then adds public profiles anyone can create.",
    bullets: ["Tools now", "Profiles next", "Marketplace in v2"],
  },
  {
    id: "m-be-positioning",
    houseId: "house-building-empires",
    room: "positioning",
    title: "Profiles for builders",
    body: "A profile can hold the links, products, tools, offers, content, proof, schedule, and contact paths someone needs in one place.",
    bullets: ["People", "Brands", "Products", "Projects"],
  },
  {
    id: "m-be-proof",
    houseId: "house-building-empires",
    room: "proof",
    title: "V1 scope",
    body: "The first version proves the public profile shape and the Building Empires site around it.",
    bullets: ["Tools and content", "Profile examples", "Flexible sections"],
  },
  {
    id: "m-be-offer",
    houseId: "house-building-empires",
    room: "offers",
    title: "Profile setup",
    body: "The first sellable offer can be setup help: turn a person, brand, product, or community into a clean public profile.",
    bullets: ["External checkout first", "Simple V1 offer", "Marketplace path later"],
    cta: { label: "Open the profile", href: "/building-empires" },
  },
  {
    id: "m-be-support",
    houseId: "house-building-empires",
    room: "support",
    title: "Marketplace path",
    body: "Selling can stay external in V1. V2 can bring profiles, setup, templates, tool stacks, and useful products into one marketplace.",
    bullets: ["Stripe", "Gumroad", "Calendly", "Shopify", "Ko-fi"],
  },
  {
    id: "m-andrea-now",
    houseId: "house-andrea",
    room: "work",
    title: "Current work",
    body: "Building the profile engine, cleaning the brand ecosystem, and turning each product into a reusable profile.",
  },
  {
    id: "m-andrea-identity",
    houseId: "house-andrea",
    room: "identity",
    title: "Builder profile",
    body: "Andrea builds public products, operating systems, books, tools, and media lanes that can share one profile shape.",
    bullets: ["Products", "Writing", "Systems", "Useful tools"],
  },
  {
    id: "m-andrea-positioning",
    houseId: "house-andrea",
    room: "positioning",
    title: "One person, many projects",
    body: "The profile needs to show the person clearly first, then connect the projects without making the visitor decode the whole ecosystem.",
    bullets: ["Andrea in Public", "Building Empires", "SimplifiedWorks"],
  },
  {
    id: "m-andrea-proof",
    houseId: "house-andrea",
    room: "proof",
    title: "Proof through shipping",
    body: "The strongest proof is the visible rhythm: weekly builds, public notes, products, books, systems, and real links that work.",
    bullets: ["Weekly build log", "Live products", "Connected brands"],
  },
  {
    id: "m-andrea-products",
    houseId: "house-andrea",
    room: "products",
    title: "Active product lanes",
    body: "Building Empires, Andrea in Public, SimplifiedWorks, Atla, Habits That Matter, and Playwave can all connect back to the same person profile.",
    bullets: ["Profile engine", "Work systems", "Habit products", "Media lanes"],
  },
  {
    id: "m-andrea-contact",
    houseId: "house-andrea",
    room: "contact",
    title: "Connect",
    body: "Use Andrea in Public as the public doorway for build notes, project context, and working together.",
    cta: { label: "Work with me", href: "https://andreainpublic.com/work-with-me" },
  },
  {
    id: "m-aip-about",
    houseId: "house-andrea-in-public",
    room: "positioning",
    title: "Public operating layer",
    body: "Andrea in Public is where the work becomes visible: build log, essays, how-tos, products, offers, and useful lessons.",
  },
  {
    id: "m-aip-offers",
    houseId: "house-andrea-in-public",
    room: "offers",
    title: "Public offers",
    body: "Consulting, products, essays, and build logs can all be surfaced from the same profile without rebuilding the identity.",
    cta: { label: "See the store", href: "https://andreainpublic.com/products" },
  },
  {
    id: "m-sw-products",
    houseId: "house-simplifiedworks",
    room: "products",
    title: "Products under SimplifiedWorks",
    body: "Atla, Imprint, and Inbetween share the work systems lane and can share login infrastructure later.",
  },
  {
    id: "m-sw-contact",
    houseId: "house-simplifiedworks",
    room: "contact",
    title: "Systems work",
    body: "SimplifiedWorks profiles can route teams to product pages, consulting offers, and SSME operating notes.",
    cta: { label: "Open SimplifiedWorks", href: "https://simplifiedworks.com" },
  },
  {
    id: "m-atla-work",
    houseId: "house-atla",
    room: "work",
    title: "Work sections",
    body: "Atla adds Projects, Products, Customers, Vendors, Reports, Files, Tasks, and KPIs on top of the same profile foundation.",
  },
  {
    id: "m-atla-support",
    houseId: "house-atla",
    room: "support",
    title: "Product support",
    body: "Product profiles can point to login, help, roadmap, or support without changing the core profile schema.",
    cta: { label: "Open Atla", href: "https://tryatla.co" },
  },
  {
    id: "m-streamo-rooms",
    houseId: "house-streamo",
    room: "games",
    title: "Streamo-specific sections",
    body: "Streamo adds Games, Streams, Clips, Badges, Watch Links, Creator Platforms, Community Posts, and VibeTags.",
  },
  {
    id: "m-streamo-schedule",
    houseId: "house-streamo",
    room: "schedule",
    title: "Live schedule",
    body: "Schedule is a simple module in V1: title, time, type, link, and visibility.",
    bullets: ["Streams", "Game nights", "Community drops"],
  },
  {
    id: "m-playwave-channels",
    houseId: "house-playwave",
    room: "channels",
    title: "Media sections",
    body: "PlaywaveStudios adds shows, channels, music, videos, publications, experiments, and media products.",
    bullets: ["Playwave Radio", "Live radio channels", "Streamo media lanes"],
  },
  {
    id: "m-playwave-schedule",
    houseId: "house-playwave",
    room: "schedule",
    title: "Shows and drops",
    body: "Media profiles can show upcoming shows, launches, office hours, or drops without becoming a calendar app.",
  },
  {
    id: "m-habits-shop",
    houseId: "house-habits",
    room: "shop",
    title: "Habit product sections",
    body: "Habits That Matter adds books, journals, courses, essays, daily tools, shop products, and habit practices.",
  },
  {
    id: "m-habits-support",
    houseId: "house-habits",
    room: "support",
    title: "Shop and support",
    body: "Habits profiles can route to books, journals, courses, and shop shelves while the checkout stays external.",
    cta: { label: "Open shop", href: "https://habitsthatmatter.com/shop" },
  },
  {
    id: "m-stop-shop",
    houseId: "house-stop",
    room: "shop",
    title: "STOP products",
    body: "STOP is a collection profile for the book, journals, quote cards, companion tools, and future product formats.",
  },
  {
    id: "m-stop-support",
    houseId: "house-stop",
    room: "support",
    title: "Buy the collection",
    body: "The STOP profile points directly to the live book, journal, and collection shelf.",
    cta: { label: "Open collection", href: "https://habitsthatmatter.com/shop" },
  },
  {
    id: "m-wd-signal",
    houseId: "house-whatdeployed",
    room: "posts",
    title: "Recent deployments",
    body: "WhatDeployed tracks what shipped in software and AI, then turns those moves into plain-English signal.",
  },
];

export const links: HouseLink[] = [
  { houseId: "house-andrea", label: "andreainpublic.com", url: "https://andreainpublic.com", type: "website" },
  { houseId: "house-andrea", label: "Instagram", url: "https://www.instagram.com/andreainpublic", type: "social" },
  { houseId: "house-andrea", label: "TikTok", url: "https://www.tiktok.com/@andreainpublic", type: "social" },
  { houseId: "house-andrea", label: "YouTube", url: "https://www.youtube.com/@andreainpublic", type: "social" },
  { houseId: "house-andrea", label: "Pinterest", url: "https://www.pinterest.com/andreainpublic", type: "social" },
  { houseId: "house-building-empires", label: "buildingempires.co", url: "https://buildingempires.co", type: "website" },
  { houseId: "house-andrea-in-public", label: "andreainpublic.com", url: "https://andreainpublic.com", type: "website" },
  { houseId: "house-simplifiedworks", label: "simplifiedworks.com", url: "https://simplifiedworks.com", type: "website" },
  { houseId: "house-atla", label: "tryatla.co", url: "https://tryatla.co", type: "product" },
  { houseId: "house-imprint", label: "tryimprint.co", url: "https://tryimprint.co", type: "product" },
  { houseId: "house-inbetween", label: "getinbetween.app", url: "https://getinbetween.app", type: "product" },
  { houseId: "house-streamo", label: "streamo.gg", url: "https://streamo.gg", type: "website" },
  { houseId: "house-playwave", label: "playwavestudios.com", url: "https://playwavestudios.com", type: "website" },
  { houseId: "house-playwave", label: "playwaveradio.com", url: "https://playwaveradio.com", type: "product" },
  { houseId: "house-habits", label: "habitsthatmatter.com", url: "https://habitsthatmatter.com", type: "website" },
  { houseId: "house-stop", label: "STOP book", url: "https://www.amazon.com/Stop-Start-Stopping-Habits-Matter/dp/B0H56MG87D", type: "shop" },
  { houseId: "house-stop", label: "STOP journal", url: "https://www.amazon.com/Stop-Habits-That-Matter-Journal/dp/B0H4Z3DLDP", type: "shop" },
  { houseId: "house-stop", label: "STOP collection", url: "https://habitsthatmatter.com/shop", type: "shop" },
  { houseId: "house-whatdeployed", label: "whatdeployed.com", url: "https://whatdeployed.com", type: "website" },
];

export const schedule: ScheduleItem[] = [
  {
    id: "sched-andrea-weekly-build",
    houseId: "house-andrea",
    title: "Weekly build rhythm",
    detail: "Ship the current product focus, capture the lesson, and connect it back to the public profile.",
    startsAt: "2026-06-22T09:00:00-04:00",
    type: "launch",
    tags: ["build", "public"],
    url: "https://andreainpublic.com/log",
    visible: true,
  },
  {
    id: "sched-profile-engine",
    houseId: "house-building-empires",
    title: "Building Empires profiles MVP",
    detail: "Ship the public profile section and prove the reusable profile shape.",
    startsAt: "2026-06-20T10:00:00-04:00",
    type: "launch",
    tags: ["mvp", "profiles"],
    url: "/building-empires",
    visible: true,
  },
  {
    id: "sched-aip-week-09",
    houseId: "house-andrea-in-public",
    title: "Week 09 build",
    detail: "Building Empires profiles become the current public build.",
    startsAt: "2026-06-22T09:00:00-04:00",
    type: "launch",
    tags: ["build log"],
    url: "https://andreainpublic.com/log",
    visible: true,
  },
  {
    id: "sched-streamo-community",
    houseId: "house-streamo",
    title: "Community night placeholder",
    detail: "A simple V1 schedule row for future live sections or stream slots.",
    startsAt: "2026-06-27T20:00:00-04:00",
    type: "stream",
    tags: ["gaming", "community"],
    url: "https://streamo.gg",
    visible: true,
  },
  {
    id: "sched-playwave-drop",
    houseId: "house-playwave",
    title: "Radio lane check",
    detail: "Use the schedule module for shows, drops, and media updates.",
    startsAt: "2026-06-25T12:00:00-04:00",
    type: "drop",
    tags: ["show", "music"],
    url: "https://playwaveradio.com",
    visible: true,
  },
];

export const items: HouseItem[] = [
  {
    id: "item-andrea-building-empires",
    houseId: "house-andrea",
    itemType: "project",
    kindLabel: "Platform",
    displayGroup: "work",
    title: "Building Empires",
    description: "Tools, content, public profiles, and the future marketplace path.",
    url: "/building-empires",
    ctaLabel: "Open profile",
    status: "building",
    tags: ["profiles", "tools", "marketplace"],
  },
  {
    id: "item-andrea-best-of-tools",
    houseId: "house-andrea",
    itemType: "pick",
    kindLabel: "Pick",
    displayGroup: "pick",
    title: "Best tools I keep coming back to",
    description: "A starter example of profile picks: tools, services, shows, vendors, books, or anything worth recommending.",
    url: "/profiles",
    ctaLabel: "View picks",
    status: "building",
    tags: ["picks", "tools", "recommendations"],
  },
  {
    id: "item-andrea-public",
    houseId: "house-andrea",
    itemType: "media",
    kindLabel: "Build Log",
    displayGroup: "work",
    title: "Andrea in Public",
    description: "The public build log, essays, products, and lessons from the work.",
    url: "https://andreainpublic.com",
    ctaLabel: "Open site",
    status: "live",
    tags: ["build-log", "essays", "public-work"],
  },
  {
    id: "item-andrea-simplifiedworks",
    houseId: "house-andrea",
    itemType: "service",
    kindLabel: "Systems",
    displayGroup: "work",
    title: "SimplifiedWorks",
    description: "Work systems, products, records, and operating tools.",
    url: "https://simplifiedworks.com",
    ctaLabel: "Open site",
    status: "live",
    tags: ["systems", "work", "products"],
  },
  {
    id: "item-andrea-habits",
    houseId: "house-andrea",
    itemType: "collection",
    kindLabel: "Books + Tools",
    displayGroup: "work",
    title: "Habits That Matter",
    description: "Books, journals, shop products, and useful habit tools.",
    url: "https://habitsthatmatter.com",
    ctaLabel: "Open site",
    status: "live",
    tags: ["books", "habits", "store"],
  },
  {
    id: "item-andrea-playwave",
    houseId: "house-andrea",
    itemType: "media",
    kindLabel: "Media",
    displayGroup: "work",
    title: "Playwave Studios",
    description: "Media, music, radio, and creator experiments.",
    url: "https://playwavestudios.com",
    ctaLabel: "Open site",
    status: "live",
    tags: ["media", "music", "studio"],
  },
  {
    id: "item-andrea-whatdeployed",
    houseId: "house-andrea",
    itemType: "tool",
    kindLabel: "Newsletter",
    displayGroup: "work",
    title: "WhatDeployed",
    description: "Plain-English signal for what shipped in software and AI.",
    url: "https://whatdeployed.com",
    ctaLabel: "Open site",
    status: "live",
    tags: ["software", "ai", "signal"],
  },
  {
    id: "item-andrea-atla",
    houseId: "house-andrea",
    itemType: "app",
    kindLabel: "Product",
    displayGroup: "product",
    title: "Atla",
    description: "A work OS for projects, products, records, and teams.",
    url: "https://tryatla.co",
    ctaLabel: "Open product",
    status: "live",
    tags: ["work-os", "systems"],
  },
  {
    id: "item-andrea-profile-engine-product",
    houseId: "house-andrea",
    itemType: "tool",
    kindLabel: "Product",
    displayGroup: "product",
    title: "Profile Engine",
    description: "One identity layer, reusable sections, and many public surfaces.",
    url: "/building-empires",
    ctaLabel: "View profile",
    status: "building",
    tags: ["profiles", "sections", "engine"],
  },
  {
    id: "item-andrea-stop-book",
    houseId: "house-andrea",
    itemType: "book",
    kindLabel: "Book",
    displayGroup: "product",
    title: "STOP book",
    description: "The direct STOP reset book on Amazon.",
    url: "https://www.amazon.com/Stop-Start-Stopping-Habits-Matter/dp/B0H56MG87D",
    ctaLabel: "Open on Amazon",
    status: "selling",
    tags: ["book", "habits"],
  },
  {
    id: "item-andrea-stop-journal",
    houseId: "house-andrea",
    itemType: "book",
    kindLabel: "Journal",
    displayGroup: "product",
    title: "STOP journal",
    description: "A companion journal for stopping what costs you.",
    url: "https://www.amazon.com/Stop-Habits-That-Matter-Journal/dp/B0H4Z3DLDP",
    ctaLabel: "Open on Amazon",
    status: "selling",
    tags: ["journal", "habits"],
  },
  {
    id: "item-profile-engine",
    houseId: "house-building-empires",
    itemType: "tool",
    title: "Profiles",
    description: "The reusable profile and section system that powers Building Empires and can support other tools later.",
    url: "/building-empires",
    price: "Setup offer TBD",
    ctaLabel: "View profile",
    status: "building",
    tags: ["profiles", "sections", "tools"],
  },
  {
    id: "item-build-log",
    houseId: "house-andrea-in-public",
    itemType: "tool",
    title: "Build Log",
    description: "Weekly product goals, weekly ships, and lessons from the work.",
    url: "https://andreainpublic.com/log",
    status: "live",
    tags: ["weekly-ships", "lessons"],
  },
  {
    id: "item-atla",
    houseId: "house-simplifiedworks",
    itemType: "app",
    title: "Atla",
    description: "A work OS for projects, products, records, and teams.",
    url: "https://tryatla.co",
    status: "live",
    tags: ["work-os", "ai"],
  },
  {
    id: "item-imprint",
    houseId: "house-simplifiedworks",
    itemType: "app",
    title: "Imprint",
    description: "Book and publishing workflows for authors and products.",
    url: "https://tryimprint.co",
    status: "building",
    tags: ["books", "authors"],
  },
  {
    id: "item-inbetween",
    houseId: "house-simplifiedworks",
    itemType: "app",
    title: "Inbetween",
    description: "Find a fair meeting place between two locations.",
    url: "https://getinbetween.app",
    status: "live",
    tags: ["places", "app"],
  },
  {
    id: "item-playwave-radio",
    houseId: "house-playwave",
    itemType: "media",
    title: "Playwave Radio",
    description: "Three live radio channels and media lanes from PlaywaveStudios.",
    url: "https://playwaveradio.com",
    status: "live",
    tags: ["radio", "channels", "music"],
  },
  {
    id: "item-streamo",
    houseId: "house-playwave",
    itemType: "community",
    title: "Streamo",
    description: "A gamer and creator product world built around vibe.",
    url: "https://streamo.gg",
    status: "live",
    tags: ["gaming", "community"],
  },
  {
    id: "item-habits-store",
    houseId: "house-habits",
    itemType: "store",
    title: "Habits That Matter Store",
    description: "The storefront for useful habit products, books, journals, and tools.",
    url: "https://habitsthatmatter.com/shop",
    ctaLabel: "Open shop",
    status: "live",
    tags: ["store", "habits"],
  },
  {
    id: "item-stop",
    houseId: "house-habits",
    itemType: "collection",
    title: "STOP Collection",
    description: "Books, journals, quote cards, and tools around stopping what costs you.",
    url: "https://habitsthatmatter.com/shop",
    ctaLabel: "Open collection",
    status: "selling",
    tags: ["book", "collection"],
  },
  {
    id: "item-stop-book",
    houseId: "house-stop",
    itemType: "book",
    title: "STOP book",
    description: "The direct STOP reset book on Amazon.",
    url: "https://www.amazon.com/Stop-Start-Stopping-Habits-Matter/dp/B0H56MG87D",
    ctaLabel: "Open on Amazon",
    status: "selling",
    tags: ["book", "amazon"],
  },
  {
    id: "item-stop-journal",
    houseId: "house-stop",
    itemType: "book",
    title: "STOP journal",
    description: "A companion journal for stopping what costs you.",
    url: "https://www.amazon.com/Stop-Habits-That-Matter-Journal/dp/B0H4Z3DLDP",
    ctaLabel: "Open on Amazon",
    status: "selling",
    tags: ["journal", "amazon"],
  },
  {
    id: "item-stop-collection",
    houseId: "house-stop",
    itemType: "collection",
    title: "STOP collection shelf",
    description: "The temporary collection shelf for STOP products.",
    url: "https://habitsthatmatter.com/shop",
    ctaLabel: "Open collection",
    status: "selling",
    tags: ["collection", "shop"],
  },
  {
    id: "item-whatdeployed",
    houseId: "house-whatdeployed",
    itemType: "tool",
    title: "Recent deployments",
    description: "A plain-English signal index for software and AI releases.",
    url: "https://whatdeployed.com",
    status: "live",
    tags: ["ai", "software", "signal"],
  },
];

export const activity: ActivityUpdate[] = [
  {
    id: "act-andrea-profile-engine",
    houseId: "house-andrea",
    title: "Profile page rebuilt",
    detail: "The public profile shape has a cover, overview, reusable sections, connected profiles, schedule, links, work, products, and activity.",
    status: "building",
    url: "/andrea-dailey",
  },
  {
    id: "act-andrea-aip",
    houseId: "house-andrea",
    title: "Andrea in Public is the build doorway",
    detail: "Weekly product goals, public notes, and shipped work route through Andrea in Public.",
    status: "live",
    url: "https://andreainpublic.com/log",
  },
  {
    id: "act-profile-engine",
    houseId: "house-building-empires",
    title: "Profiles are the next build",
    detail: "The MVP is the public site, profile pages, flexible sections, products, links, and updates.",
    status: "building",
  },
  {
    id: "act-aip-log",
    houseId: "house-andrea-in-public",
    title: "Build log is active",
    detail: "Weekly product goals and weekly ships are now the public rhythm.",
    status: "live",
    url: "https://andreainpublic.com/log",
  },
  {
    id: "act-stop",
    houseId: "house-habits",
    title: "STOP Collection moved into the store",
    detail: "STOP lives as a collection under Habits That Matter.",
    status: "selling",
    url: "https://habitsthatmatter.com/shop",
  },
  {
    id: "act-radio",
    houseId: "house-playwave",
    title: "Playwave Radio has live channels",
    detail: "The radio product is a real media lane inside PlaywaveStudios.",
    status: "live",
    url: "https://playwaveradio.com",
  },
];
